### ISSUE TITLE
Hi I am quite a newbie to python and I found a problem

### ISSUE THREAD

**Issue by Classditcher** [supersu-man/ZoomAutoLogin#1]
Dear supersu-man,
Thank you for the awesome codes. I copied exactly as you wrote in the youtube video, but I get an error like the following:

if datetime.now().hour == int(i[1].split(':')[0]) and datetime.now().minute == int(i[1].split(':')[1]):

ValueError: invalid literal for int() with base 10: ' '

What would have been the problem? I don't get the problem when I put while False instead of while True. But it doesnt even run anything, it is just blank. 
Also I would really appreciate if you knew how to add dates to the codes!

Thank you.

**Comment by supersu-man** [comment]
In data.py file, while giving the start time and end time of the meeting , do not give anything other than numbers and colon, not even spaces .
For example:
"13:00"

Not like these:
"13", "13: ", 13, "13 : 00".

**Comment by Classditcher** [comment]
![화면 캡처 2021-01-13 114050](https://user-images.githubusercontent.com/71779266/104399569-48cf5480-5594-11eb-9f5c-43c4b89d20ef.png)

**Comment by Classditcher** [comment]
Thanks for the reply! I put the time in the above format but I still have errors...

**Comment by supersu-man** [comment]
Can you send me the full code (both the files)

**Comment by Classditcher** [comment]
[python.zip](https://github.com/supersu-man/ZoomAutoLogin/files/5807474/python.zip)


thank  you!

**Comment by supersu-man** [comment]
> 
> 
> [python.zip](https://github.com/supersu-man/ZoomAutoLogin/files/5807474/python.zip)
> 
> thank you!

There's space in front of the meeting link in data.py.

**Comment by Classditcher** [comment]
Hi thanks for the comment. Now I have this error
![image](https://user-images.githubusercontent.com/71779266/105323002-f550ac80-5c0c-11eb-8d06-856092963583.png)
What should I do?
Thank you.

**Comment by supersu-man** [comment]
> Hi thanks for the comment. Now I have this error
> ![image](https://user-images.githubusercontent.com/71779266/105323002-f550ac80-5c0c-11eb-8d06-856092963583.png)
> What should I do?
> Thank you.

Send me the pic of the other file too.

**Comment by Classditcher** [comment]
![image](https://user-images.githubusercontent.com/71779266/105328729-b3773480-5c13-11eb-8fb5-81d7b3a66ddd.png)

**Comment by supersu-man** [comment]
Copy the code properly dude.![IMG_20210121_145433.jpg](https://user-images.githubusercontent.com/35676632/105330777-af89e900-5bf8-11eb-8360-715b5d0afbcc.jpg)

There another '[' and ']' in the beginning and ending inside lst

**Comment by Classditcher** [comment]
Holy goodness, it finally works master. Thank you so much!!

**Comment by Classditcher** [comment]
![image](https://user-images.githubusercontent.com/71779266/105335162-11f3e100-5c1b-11eb-93e6-928fb2592838.png)
Hi right now opening the link has no problem, however, ending the meeting is the problem. I have made pressing x as an exit button in the Zoom setting and reflected that in the code. However, it doesnt work. Do you have any idea why?

**Comment by supersu-man** [comment]
Haha, Please copy the code properly. Line 23 , copy from my code. Instead i[1] it should be i[2].

**Comment by Classditcher** [comment]
Thank you so much Supersuman!!! It will most definitely work then
