### ISSUE TITLE
My Highest Honor, I wonder how I could additionally automatically type out my name in zoom chat!

### ISSUE THREAD

**Issue by Classditcher** [supersu-man/ZoomAutoLogin#2]
Dear Master,

Hi! As i said in the title, I tried it myself but to no avail. I have changed the shortcut to opening chat as 't'.
![image](https://user-images.githubusercontent.com/71779266/105432385-e44e7c80-5c9a-11eb-8a5d-6922227dfc7e.png)
It looks like I need to use a different function to type out such a long string as my name. Do you have any suggestion, sir?

Thank you as always.

**Comment by supersu-man** [comment]
Sorry for the late reply, haven't been active on github for months. 
Anyways, [this link](https://pythonhosted.org/pynput/keyboard.html) should help you.
According to that link, you can use "keyboard.type()" to type a phrase. If it doesn't help make a custom function, pass your text you want to type, and make it press each letter.
I also suggest you to put shortcut keys something other than alphabets, if you are going to type something in chat box.
