### ISSUE TITLE
files are not working

### ISSUE THREAD

**Issue by malharkshirsagar** [supersu-man/ZoomAutoLogin#3]
whenever i excutive the main files they are working but zoom isnt opening

**Comment by supersu-man** [comment]
Need more information on why it is not working for you.
Make sure to read the [Requirements](https://github.com/supersu-man/ZoomAutoLogin/blob/main/README.md#requirements) in the newly added [README](https://github.com/supersu-man/ZoomAutoLogin/blob/main/README.md) file.
